remote_theme: coursweb/jk-theme
title: Feedback
description: Documentation sur les méthodes de feedback.
lang: fr-FR
robots: index, follow
chapters:
 - title: Cours-web
   url: https://cours-web.ch/
 - title: Créativité
   url: https://cours-web.ch/crea/
 - title: Feedback
   url: https://cours-web.ch/feedback/
 - title: Méthodes Agiles
   url: https://cours-web.ch/agile/

   # Footer content
# Content is split in three columns.   
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2017–2022</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/coursweb/feedback">Lien Github</a></li></ul>
